### ISSUE TITLE
invalid mode

### ISSUE THREAD

**Issue by shantanuo** [EagleChen/docker_go_mysql_elasticsearch#1]
I am getting this error while running the command mentioned in readme.

docker: Error response from daemon: Invalid bind mount spec "/tmp/go_mysql_river.toml:/go_mysql_river.toml:r": invalid mode: r.
See 'docker run --help'.

**Comment by EagleChen** [comment]
@shantanuo 

It should be "ro" ( which means readonly) for current version of docker.
One year ago when I created this repo, "r" means "readonly".

The README file has been updated.
